### ISSUE TITLE
Can I npm install ?

### ISSUE THREAD

**Issue by mengru0102** [KeeeX/qrcodejs#2]
I would like to ask whether I can npm install it derictly or not in my project, and what is the name of it. I find the npm that  ‘qrcode’ and  ‘qrcodejs2’ are not yours.

**Comment by fladna9** [comment]
Hi @mengru0102, just saw your issue and mail.
There were no npm package before (not needed), there's one now:
`npm i @keeex/qrcodejs-kx`

**Comment by fladna9** [comment]
Closing the issue, feel free to reopen if it doesn't work.

**Comment by ghost** [comment]
thanks your npm package. Just I try it and find it can't work normally, it shows:  __WEBPACK_IMPORTED_MODULE_4__keeex_qrcodejs_kx___default.a is not a constructor

**Comment by ghost** [comment]
I use it "import QRCode from '@keeex/qrcodejs-kx'" in my VUE project now. it shows: __WEBPACK_IMPORTED_MODULE_4__keeex_qrcodejs_kx___default.a is not a constructor.
And I use it "import QRCode from 'qrcodejs2" before you fixed it, and no problems except overflows

**Comment by ghost** [comment]
And I find it has only four files in folder, they're LICENCE, package.json, qrcode.min.js, README.md
I think whether it  is short of something.

**Comment by fladna9** [comment]
Hi @mengru19950102 (profile changed?),
I'll see this with my colleague tomorrow (it's 10:30 PM here ^_^) to test the NPM package.

For the "short of file" package, all other files are only needed for demo purposes.
- LICENSE is mandatory, and is the license file,
- README.md is the readme file,
- qrcode.min.js is the minified qrcodejs version,
- package.json	is the npm package "definition"

As for non included:
- index-svg.html is only a demo HTML file (not required)
- index.html is only a demo HTML file (not required)
- qrcode.js is the non minified version of qrcodejs (not required).

Will come back to you soon, maybe with a package update.
Reopening issue.

**Comment by ghost** [comment]
ok, waiting for your reply.

**Comment by ghost** [comment]
I beg your pardon……whether you test the package, bacause my project is urgent. Wish for your help.

**Comment by fladna9** [comment]
If your project is urgent, i might recommend you to wget the file via the command:
`https://raw.githubusercontent.com/KeeeX/qrcodejs/master/qrcode.min.js`
and use this file. 
I'm sorry but i don't have time to dig this NPM package oddities further in the next following days. I'll update this as I have time to do it.

**Comment by CleyFaye** [comment]
In the meantime, you can try https://github.com/CleyFaye/qrcodejs to see if it fix your issue with webpack.

**Comment by mengru19950102** [comment]
@CleyFaye  Whether can I bpm install derictly? And What's name ?

**Comment by ghost** [comment]
@CleyFaye Whether can I npm install derictly? And What's name ?

**Comment by ghost** [comment]
@CleyFaye ok.I will have a try. Thanks.

**Comment by CleyFaye** [comment]
Just use
`npm install https://github.com/CleyFaye/qrcodejs.git`
and
`import QRCode from '@keeex/qrcodejs-kx`
to test.
I'm afraid if this doesn't work I won't be able to put much more time on this either.

**Comment by ghost** [comment]
It's normal now. Can you help to publish a npm package ?

**Comment by craig-wagner** [comment]
FWIW, I did:

`npm i @keeex/qrcodejs-kx`

Then in my vue component I added:

`import QRCode from '@keeex/qrcodejs-kx/qrcode.min.js';`

I was then able to use the object to create a QR code:

```
            const qrcode = new QRCode(document.getElementById('qrcode'), {
                text: baseUrl + this.$route.query.o,
                width: 150,
                height: 150,
                colorDark: '#000',
                colorLight: '#FFF',
                correctLevel: QRCode.CorrectLevel.H,
            });
```

**Comment by CleyFaye** [comment]
Turns out in the meantime my fix for webpack was merged and published on npmjs.
