### ISSUE TITLE
Cannot read property '3' of undefined

### ISSUE THREAD

**Issue by araad1992** [KeeeX/qrcodejs#4]
Hi, i try to use this library but obtain this error message "Cannot read property '3' of undefined".

I am implementing as follows:

In javascript
_cqr = function construirQR(){	
	var idCajero = $("#idCajero").val();
	var idTransaccion = $("#idTransaccion").val();
	var template = $("#huellaTemp").val();        
        var valor = idCajero + "%" + idTransaccion + "%" + template; 
	var qrcode = new QRCode(document.getElementById("qrCode"), {
		text: valor,
		width: 300,
		height: 300,
		colorDark : "#000000",
		colorLight : "#ffffff",
		correctLevel : QRCode.CorrectLevel.H
	});
}

**Comment by CleyFaye** [comment]
I just tested your code sample replacing jQuery calls with placeholder strings and it works fine, so I'm closing this. If you still have this issue (sorry for the delay btw), feel free to reopen with more details.
